# Use official Node.js LTS image
FROM node:20

# Set working directory
WORKDIR /node_app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install mysql2

# Copy the rest of the app
COPY . .
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh


# Expose port
EXPOSE 3000

# Start the app
CMD ["/usr/local/bin/wait-for-it.sh", "db:3306", "--", "node", "index.js"]
